### ISSUE TITLE
Create HTML structure for widget

### ISSUE THREAD

**Issue by RadValentin** [uberVU/github-changelog#3]
## Need

Build a HTML structure for the widget that allows for customization and that can be used by the plugin
## Deliverables
- Add info in `README.md` detailing the HTML structure
## Solution

We will have the plugin contained within a wrapper called `changelog-wrapper`. Inside of it there are two elements:
1. _Notification button_ - This is what shows up when new notifications are available.
2. _Notification list_ - This list shows the notification area, it will contain number of notification items.

The button will contain a badge that will show the number of new notifications. The list will be made up of multiple items, each corresponding to a notification. The list can be positioned using a class on the wrapper. There will also be a footer inside the list that will contain the reload button.

_Notification item_ - composed of two elements, a label and text content.
#### TODO
- [x] define a notification button with a badge
- [x] define options to style the button: size and type
- [x] define a notification list
- [x] define a notification item with content text and an optional label
- [x] define options for positioning the list in relation to the button
- [x] define an element to contain a reload button (list footer)

cc: @skidding @catalinmiron

**Comment by RadValentin** [comment]
HTML Structure has been included in `README.md`, we can close this issue now

**Comment by ovidiuch** [comment]
Cool. Closing this but can you please use the same class prefix as the main class? `github-changelog-` vs `changelog-`
