### ISSUE TITLE
Create LESS styling for widget

### ISSUE THREAD

**Issue by RadValentin** [uberVU/github-changelog#4]
## Need

Build LESS styling to support the HTML structure so that it can be integrated with the plugin
## Deliverables
- LESS files and the generated CSS for positioning and styling the notification list. The styling will be applied to the HTML structure described below and should match the attached wireframe.

_HTML structure_

``` html
<div class="github-changelog">
  <a class="github-changelog-btn" href="#">
    New updates!
    <span class="github-changelog-badge">2</span>
  </a>

  <div class="github-changelog-list">
    <ul>
      <li>
        <span class="github-changelog-label"> issue label </span>
        <p> issue title </p>
      </li>
    </ul>
    <div class="github-changelog-footer">
      <a class="github-changelog-btn github-changelog-btn-reload">Reload</a>
    </div>
  </div>
</div>
```

_Wireframe_
![list positioning](https://cloud.githubusercontent.com/assets/3300066/2999278/1407e078-dd14-11e3-941c-3cce9f10377c.png)
## Solution

We'll need to create styling for the following:
1. A notification button with a badge to show the number of new notifications
2. A notification list that can be positioned according to it's css class with 4 main positions: `top`, `bottom`, `left` and `right`. Each of these positions can be modified by providing a second class: `pull-left` and `pull-right` for vertical positions and `pull-top` for horizontal positions. The purpose here is to make the list usable in any positioning scenario.
3. A footer element for the notification list that will contain a reload button.
4. Notification items that will show up in the list. These will have a label and content text.
5. A utility class `.closed` to hide the list
#### Prerequisites
- [LESS](http://lesscss.org/)
- Compile LESS to CSS [Grunt plugin](https://github.com/gruntjs/grunt-contrib-less)
- HTML Structure [wiki page](https://github.com/uberVU/github-changelog/wiki/HTML-Structure)
#### TODO
- [x] Create a LESS skeleton to support the HTML structure
- [x] Add styles for the button, its appearance and size
- [x] Extend the button styling to support a badge element
- [x] Add styles for the notification list
- [x] Add styles for positioning the notification list
- [x] Add styles for the notification list footer
- [x] Define LESS variables for changing the various styling options
- [x] Define utility class to hide the list

cc: @skidding @catalinmiron

**Comment by ovidiuch** [comment]
The solution is good, the deliverable however is very thin. Here's why I would do:
1. This is a styling issue. So this implies you have a structure you need to style, right? OK, put a html snippet with the entire DOM structure expected in the issue description. OK, so you have the **input** (the HTML)
2. You also need an **output.** Well it's either a design, or a sketch. That's what styling does, right? Translate meaningless DOM nodes into shapes we humans see and understand, using a language the browser understands. You can take a piece of paper and draw the button, the list, and everything (without regard to colors, details, etc.), then you can draw multiple screens for each positioning available and for each state available (with updates, after user clicked and opened list, etc.) After you have this sketches 1. you made sure you're thinking everything through, and 2. you take a photo and upload it in the issue description; any reader will instantly figure out what you want to deliver.

This transforms this issue into a function. f(HTML)=>Styled widget

(I know you already have a lot of CSS and this is about rewriting it in LESS, but discard previous unorganized work from the planning process and do things the right way.)
